### ISSUE TITLE
Entire Codeblock should be grey or not grey, not just the code line.

### ISSUE THREAD

**Issue by linuxguy123** [ken-okabe/vscode-markdown-note#4]
This:
![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1920754/2f3d626c-608e-4eaf-9179-95f2854d784b)

formats to this:
![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1920754/e77034c7-1cad-403a-87bb-4dc041f00e42)

The background (grey) on just the code itself makes it look messy when large blocks of code are displayed:
![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1920754/2ee93a00-5759-4a8d-82dd-cbe22dc15dbc)

It would be nicer if the entire block's background was grey (I prefer this) or if the block's background was white.  Jupyter does this.

![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1920754/11b887df-5a9a-4623-9d22-30b76928ca3e)

Maybe this could be a setting in VSCode ?  I'd like it if the entire codeblock had a grey background so it sets off from plain text.

**Comment by ken-okabe** [comment]
This does not happen in my environment.

I just want to confirm if you have followed the Getting Started process.

https://github.com/ken-okabe/vscode-markdown-note?tab=readme-ov-file#-getting-started

Doing so, the VSCode setting should be sorted without issues.

**Comment by ken-okabe** [comment]
![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1316994/aa74eced-780e-4340-9502-738583cec4c4)

**Comment by ken-okabe** [comment]
> This: ![image](https://private-user-images.githubusercontent.com/1920754/315557549-2f3d626c-608e-4eaf-9179-95f2854d784b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTg1NDQsIm5iZiI6MTcxMjIxODI0NCwicGF0aCI6Ii8xOTIwNzU0LzMxNTU1NzU0OS0yZjNkNjI2Yy02MDhlLTRlYWYtOTE3OS05NWYyODU0ZDc4NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDgxMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZmN2Y0OTljMzFhYWNmMTI4YWM3YjIyMjg1Y2JlNzNlYzY4NzQzZjRkZjBmMDlhMTVkNzNlYjg5ZTE2OGQ3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZsCUOXyoWtOtzqgypDdKwEMd0Fqq5DXIvuafuKc4lvE)
> 
> formats to this: ![image](https://private-user-images.githubusercontent.com/1920754/315557765-e77034c7-1cad-403a-87bb-4dc041f00e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTg1NDQsIm5iZiI6MTcxMjIxODI0NCwicGF0aCI6Ii8xOTIwNzU0LzMxNTU1Nzc2NS1lNzcwMzRjNy0xY2FkLTQwM2EtODdiYi00ZGMwNDFmMDBlNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDgxMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODlmYzllNDYyNTJhMjM5YTk5YzliYThlMGMyMWQzMTFkN2Q1YTFmZWUzYzlkMjAwNjU2YWY2MzU4YmVlNzEwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nweym3tmUvaLOuuR6eunFnWHC--gaSH1tq3Hn3EePj0)
> 
> The background (grey) on just the code itself makes it look messy when large blocks of code are displayed: ![image](https://private-user-images.githubusercontent.com/1920754/315558007-2ee93a00-5759-4a8d-82dd-cbe22dc15dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTg1NDQsIm5iZiI6MTcxMjIxODI0NCwicGF0aCI6Ii8xOTIwNzU0LzMxNTU1ODAwNy0yZWU5M2EwMC01NzU5LTRhOGQtODJkZC1jYmUyMmRjMTVkYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDgxMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDNlNjZmYzAzMmQxMmM3Zjc3YmRiMWM1ZGRlNDVjY2JlMmM0ODFmMDUwNmY4ZmI5OTRiOTRhYTg0NGU0ZWZhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y-JDOUZnvTFAstNkhN8zk-rcvGVUJ867Aw0pcAF82qQ)

Actually, I confirm this without an internet connection.

The reason is the CSS is configured from the internet.

![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1316994/180549c5-9656-45d3-ae65-e8fe2f21ab74)

I don't know if it's proper to make default use of some local CSS files.

**Comment by ken-okabe** [comment]
fixed the issue for offline mode on update.

**Comment by ken-okabe** [comment]
fixed the issue for offline mode on update.

**Comment by ken-okabe** [comment]
fixed the issue for offline mode on update.
